### ISSUE TITLE
Quant Assignment 1 is ready

### ISSUE THREAD

**Issue by brianaflynn** [SES-5215-F2020/bflynn-quant#1]
Hi Carole and Sara,

The html and .rmd files are ready for viewing, entitled "Assignment1". Hope you both had a nice weekend!

Briana

**Comment by c-voulgaris** [comment]
This looks great! Since you submitted it early, I'm happy to give some early feedback in case you want to revise it at all and resubmit before the deadline. 

The only issue I see upon a quick read-through (and it's a very minor issue) is that you have one variable included in the last column of your dataset (the one about the presence of children) that isn't included in your initial list of variables.

**Comment by brianaflynn** [comment]
Thank you, Carole! I just made that change to include the variable about presence and age of children in my list and a revised version is now saved as "Assignment1Revised".
